version: '3'
services:
  kong:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    networks:
      - arithmetic

networks:
  arithmetic:
    external: true
