apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-kong
  labels:
    app: arithmetic-kong
spec:
  selector:
    matchLabels:
      app: arithmetic-kong
  replicas: 1
  template:
    metadata:
      labels:
        app: arithmetic-kong
    spec:
      containers:
        - name: arithmetic-kong
          image: "vitor96k/arithmetic-kong:3.1.2"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 100m
              memory: 350Mi
