apiVersion: apps/v1
kind: Deployment
metadata:
  name: arithmetic-kong
  labels:
    app: arithmetic-kong
spec:
  selector:
    matchLabels:
      app: arithmetic-kong
  replicas: 1
  template:
    metadata:
      labels:
        app: arithmetic-kong
    spec:
      containers:
        - name: arithmetic-kong
          image: "vitor96k/arithmetic-kong"
          volumeMounts:
            - name: logs-volume
              mountPath: /log
              subPath: kong/log
          resources:
            requests:
              cpu: 200m
              memory: 800Mi
            limits:
              cpu: 300m
              memory: 1000Mi
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-volume-claim
