apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

## To change the newName and newTag just run: kustomize edit set image vitor96k/arithmetic-kong:4.0.0
images:
- name: vitor96k/arithmetic-kong
  newTag: 3.3.9
