name: push-image-develop

on:
  push:
    tags:
      - "*"

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "tag_name=$(git describe --tags)" >> $GITHUB_OUTPUT

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: vitor96k/arithmetic-kong:${{ steps.vars.outputs.tag_name }}
      #     platforms: linux/amd64,linux/arm64

      - name: Checkout K8s Repository
        uses: actions/checkout@v3
        with:
          repository: vitoraderaldo/arithmetic-k8s
          ref: develop

      - name: 'Install Kustomize'
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.1.0'
        
      - name: 'Kustomize build'
        run: |
          cd kong/k8s
          kustomize edit set image vitor96k/arithmetic-kong:${{ steps.vars.outputs.tag_name }}

      - name: Configure Git User
        run: |
          git config --global user.email "action@hithub.com"
          git config --global user.name "GitHub Action"

      - name: 'Commit '
        run: |
          git add .
          git commit -m "Update image tag to ${{ steps.vars.outputs.tag_name }}"

      - name: Push kustomization.yaml
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          destination-github-username: vitoraderaldo
          destination-repository-name: arithmetic-k8s
          user-email: action@hithub.com
          target-branch: develop
